import Head from "next/head";
import PermLinksList from "../../components/PermLinksList/PermLinksList";
import Toolbar from "../../components/Toolbar/Toolbar";
import styles from '../../styles/Home.module.css'

function Author({ links, author }) {
  return (
    <div>
      <Head>
        <title>Índice da Permanência</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Toolbar subTitle={author[0].name} />
      
      <main className={styles['main--page']}>
        <PermLinksList links={links} />
      </main>
    </div>

  )
}

export async function getStaticPaths() {
  const res = await fetch('http://localhost:3001/authors')
  const authors = await res.json();

  const paths = authors.map((author) => ({
    params: { id: author._id }
  }));

  return { paths, fallback: false }
}

export async function getStaticProps({ params }) {
  const res = await fetch(`http://localhost:3001/authors/${params.id}`)
  const data = await res.json();

  return { props: { ...data } }
}

export default Author