import Head from 'next/head'

function Authors({ authors }) {
    return (
        <div>
            <Head>
                <title>Índice da Permanência</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <ul>
                {authors.map((author) => {
                    return <li>{author.name}</li>
                })}
            </ul>
        </div>

    )
}

export async function getServerSideProps() {
    const rest = await fetch('http://localhost:3001/authors')
    const authors = await rest.json()

    return {
        props: {
            authors
        }
    }
}

export default Authors