import Head from 'next/head'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import AuthorCard from '../components/AuthorCard/AuthorCard'
import Toolbar from '../components/Toolbar/Toolbar'
import styles from '../styles/Home.module.css'

function Authors({ authors }) {
  const [text, setText] = useState("");
  const [authorsList, setAuthorsList] = useState(authors)

  useEffect(() => {
    setAuthorsList(
      authors.filter((author) => {
        return author.name.toLowerCase().indexOf(text.toLowerCase()) > -1;
      })
    );
  }, [text]);

  return (
    <div>
      <Head>
        <title>Índice da Permanência</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toolbar showSearch={true} text={text} setText={setText} />

      <main className={styles['main--page']}>
        <div className={styles.authors}>
          {authorsList.sort((a, b) => {
            const nameA = a.name.toLowerCase(), nameB = b.name.toLowerCase();
            return nameB > nameA ? -1 : 1;
          }).map((author, index) => {
            return <AuthorCard {...author} key={index} />
          })}
        </div>
      </main>
    </div>

  )
}

export async function getServerSideProps() {
  const res = await fetch('http://localhost:3001/authors')
  const authors = await res.json()

  return {
    props: {
      authors
    }
  }
}

export default Authors