import Head from 'next/head'
import Link from 'next/link'
import Toolbar from '../components/Toolbar/Toolbar'
import styles from '../styles/Home.module.css'

function Authors({ authors }) {
  return (
    <div>
      <Head>
        <title>Índice da Permanência</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toolbar />
      <main className={styles['main--page']}>
        <ul>
          {authors.map((author, index) => {
            return <li key={index}><Link href={'/authors/' + author._id}><a>{author.name}</a></Link></li>
          })}
        </ul>
      </main>
    </div>

  )
}

export async function getServerSideProps() {
  const res = await fetch('http://localhost:3001/authors')
  const authors = await res.json()

  return {
    props: {
      authors
    }
  }
}

export default Authors