import Head from 'next/head'
import Link from 'next/link'
import Toolbar from '../components/Toolbar/Toolbar'
import styles from '../styles/Home.module.css'
import '@fortawesome/fontawesome-svg-core/styles.css';
// Prevent fontawesome from adding its CSS since we did it manually above:
import { config } from '@fortawesome/fontawesome-svg-core';

config.autoAddCss = false; /* eslint-disable import/first */
export default function Home() {
  return (
    <div>
      <Head>
        <title>Índice da Permanência</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toolbar />

      <main className={styles['main--page']}>

        <h3>Este projeto é uma iniciativa pessoal,
          sem vinculação com o <a href='https://permanencia.org.br' target='_blank' rel='noreferrer'>site</a> da Permanência ou com qualquer objetivo financeiro.
        </h3> <br />

        <h3>O fim deste website é exibir índices dos artigos do site de uma forma mais organizada e prática. </h3>

        <br />

        <h3>Também fiz isso para adquirir novos conhecimentos em programação web e scrapping. </h3>

        <br />
        <br />
        <h3>
          Para mais informações, não deixe de visitar o <a href='https://github.com/Guilherme-Valle/permanencia-indice'
            rel='noreferrer'
            target='_blank'>repositório deste site</a>.</h3>

        <h2>Salve Maria!</h2>

      </main>
    </div>

  )
}
