import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Índice da Permanência</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles['main--page']}>

        <h1>Índice da Permanência</h1>

        <h2>Links:</h2>

        <Link href="/authors">
          <h3> <a>Autores</a></h3>
        </Link>
      </main>
    </div>

  )
}
